// 资讯源与分类配置

const USER_PREFERENCES = {
  coreTopics: [
    "AI",
    "人工智能",
    "大模型",
    "LLM",
    "OpenAI",
    "ChatGPT",
    "GPT",
    "Claude",
    "Anthropic",
    "Agent",
    "智能体",
    "AI Agent",
    "OpenClaw",
    "AI编码",
    "AI编程",
    "数字员工",
    "AI转型",
    "MCP",
    "Model Context Protocol",
    "RAG",
    "向量数据库",
    "多模态",
    "文生图",
    "文生视频",
    "AI硬件",
    "AI芯片",
    "GPU",
  ],
  wechatAccounts: [
    "数字生命卡兹克",
    "agent橘",
    "卡尔的ai沃茨",
    "赛博禅心",
    "通往agi之路",
    "虎嗅app",
    "founder park",
    "程序员鱼皮",
    "仓何",
    "歸藏的ai工具箱",
    "花叔",
    "datawhale",
    "程序猿玩ai",
  ],
};

// 主抓取脚本依赖的站点配置
const SOURCES = {
  wechat: USER_PREFERENCES.wechatAccounts.map((name) => ({
    name,
    query: `${name} 最新文章`,
  })),
  domestic: [
    { name: "36Kr", rss: "https://36kr.com/feed" },
    { name: "虎嗅", rss: "https://www.huxiu.com/rss/0.xml" },
    { name: "极客公园", rss: "https://www.geekpark.net/rss" },
  ],
  international: [
    { name: "TechCrunch", rss: "https://techcrunch.com/feed/" },
    { name: "The Verge", rss: "https://www.theverge.com/rss/index.xml" },
    { name: "Ars Technica", rss: "https://feeds.arstechnica.com/arstechnica/index" },
  ],
};

// 文章分类，和前端筛选保持一致
const CATEGORIES = {
  AI: [
    "ai",
    "人工智能",
    "chatgpt",
    "openai",
    "claude",
    "anthropic",
    "gemini",
    "llm",
    "gpt",
    "大模型",
    "智能体",
    "agent",
    "机器学习",
    "深度学习",
  ],
  产品: [
    "产品",
    "应用",
    "体验",
    "发布",
    "更新",
    "功能",
    "feature",
    "app",
    "iphone",
    "android",
    "google",
    "apple",
  ],
  创业: [
    "创业",
    "融资",
    "投资",
    "vc",
    "pe",
    "ipo",
    "估值",
    "公司",
    "初创",
    "startup",
    "商业",
  ],
  硬件: [
    "芯片",
    "gpu",
    "cpu",
    "硬件",
    "半导体",
    "服务器",
    "显卡",
    "nvidia",
    "英伟达",
    "手机",
    "机器人",
    "汽车",
  ],
};

module.exports = {
  USER_PREFERENCES,
  SOURCES,
  CATEGORIES,
};
